### PR TITLE
Update thermo.py

### PR DESCRIPTION
**Pull request by nwinner**
Add all corrections, not specifically Freysoldt.

### CODE REVIEW

**Comment by jmmshn** [comment]
So I had it add up the corrections before since the old implementation kept track of the electrostatic and alignment parts separately as just a dictionary.  Now all the components should be part of an object returned for a particular scheme I don't think you should add them.

**Comment by nwinner** [comment]
That's a good point. The current implementation should not hard code "freysoldt" though. Not sure how to resolve this. Any ideas?

**Comment by jmmshn** [comment]
Just addition some kind of default either in the class or function call should suffice.
I kinda just added other corrections last week so I haven't gotten around to it yet.

**Comment by nwinner** [comment]
I guess it depends on if you want to handle compatibility natively or in atomate2. Wherever you do that, then the schemas there will assign corrections and ensure that you don't accidentally put two electrostatic corrections or whatever.

If its done elsewhere, then just sum all the values. If you want to do it in here, then we need to rebuild the DefectCompatibility that was in the old version.

**Comment by jmmshn** [comment]
Ideally compatability should be handled at the `entry` level so the `FormationEnergyDiagram` should not have to worry at all.  It just needs to know which correction was used.

**Comment by nwinner** [comment]
Okay I'll do something with compatibility and make a new PR later.

**Pull request closed without merging**
