### PR TITLE
Plotting

### PR DESCRIPTION
**Pull request by nwinner**
First pass at plotting functionality for new defects module.

### CODE REVIEW

**Comment by jmmshn** [comment]
@nwinner can you add a small test to cover the plotting?

**Comment by nwinner** [comment]
> @nwinner can you add a small test to cover the plotting?

There's a small test now. Doesn't do much at the moment just makes sure no errors are raised basically

**Comment by nwinner** [comment]
@jmmshn Code coverage is not high enough for plotting. The things not covered by tests are actually covered, but because of the structure using a fixture instead of putting it directly in pytest, I don't think its picked up. 

If you want to be super strict about coverage, I can try some other ways to get it to recognize the coverage, otherwise it's probably ready to merge.

**Comment by jmmshn** [comment]
no worries I was a bit busy writing this week. I will merge and release now.

**Pull request merged**
